### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/Todoser#9]
Во время перехода БД с sqlite на pg стоит сразу использовать docker-compose для самой БД и Админки
Необходимо добавить в корень проекта файл docker-compose.yml
Ориентировчное содержание

```yml
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
  db:
    image: postgres:13.5
    container_name: postgres_db
    restart: always
    ports:
      - "127.0.0.1:54320:5432"
    env_file: .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - turreta_network
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - turreta_network
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db

networks:
  turreta_network:
    driver: bridge

volumes:
    elastic_data:
      driver: local
    postgres_db:
```

**Comment by vovs03** [comment]
В `Markdown` для корректного отображения синтаксиса языков 
`yml`, `ruby`, `html` и т.д.
используется обрамления кода для многострочников

> \```yml
> ...
> \```

> без использования `\` соотвественно

---

@XaoGao, я внёс корректировку в примерном содержании файла `docker-compose.yml`
Вчера, кстати этот вопрос в тг-чате всплывал.

**Comment by XaoGao** [comment]
На данный момент файл выглядит так:
```yml
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:

```
есть проблема со строкой
```yml
    ports:
      - "${DATABASE_PORT}:5432"
```
Приходиться прописать вручную в файле кокретный порт
